INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Back Squat', 'Anaerobic', 'Legs', 'Core', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Front Squat', 'Anaerobic', 'Legs', 'Core', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Conventional Deadlift', 'Anaerobic', 'Legs', 'Back', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Sumo Deadlift', 'Anaerobic', 'Legs', 'Back', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Barbell Bench Press', 'Anaerobic', 'Chest', 'Arms', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Barbell Overhead Press', 'Anaerobic', 'Shoulders', 'Arms', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Pull Up', 'Anaerobic', 'Back', 'Arms', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Push Up', 'Anaerobic', 'Chest', 'Arms', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Run', 'Aerobic', 'Cardio', 'Legs', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Swim', 'Aerobic', 'Cardio', 'Back', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Row', 'Aerobic', 'Cardio', 'Back', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Bike', 'Aerobic', 'Cardio', 'Legs', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Box Jump', 'Mobility', 'Legs', 'None', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Shuttle Sprints', 'Mobility', 'Legs', 'Cardio', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Lateral Plyometric Jumps', 'Mobility', 'Legs', 'Core', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('High Knee Drills', 'Mobility', 'Legs', 'Cardio', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Side-to-Side Drills', 'Mobility', 'Legs', 'Core', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Downward Facing Dog', 'Mobility', 'None', 'None', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Warrior 1', 'Mobility', 'None', 'None', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Warrior 2', 'Mobility', 'None', 'None', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Plank Pose', 'Mobility', 'None', 'None', 1);
INSERT INTO fitkick_exercise (name, exercise_type, primary_muscles, secondary_muscles, owner_id) VALUES ('Cat-Cow Stretch', 'Mobility', 'None', 'None', 1);

INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 1, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 2, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 3, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 4, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 5, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 6, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 7, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 8, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 9, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 10, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 11, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 12, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 13, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 14, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 15, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 16, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 17, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 18, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 19, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 20, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 21, 1);
INSERT INTO fitkick_exerciseinfo (notes, exercise_id, owner_id) VALUES ('', 22, 1);


INSERT INTO fitkick_workout (name, notes, owner_id) VALUES ('Back Day', '', 1);
INSERT INTO fitkick_workout (name, notes, owner_id) VALUES ('Chest Day', '', 1);

INSERT INTO fitkick_workout_exercises (workout_id, exercise_id) VALUES (1, 3);
INSERT INTO fitkick_workout_exercises (workout_id, exercise_id) VALUES (1, 4);
INSERT INTO fitkick_workout_exercises (workout_id, exercise_id) VALUES (1, 7);
INSERT INTO fitkick_workout_exercises (workout_id, exercise_id) VALUES (1, 10);
INSERT INTO fitkick_workout_exercises (workout_id, exercise_id) VALUES (2, 5);
INSERT INTO fitkick_workout_exercises (workout_id, exercise_id) VALUES (2, 6);
INSERT INTO fitkick_workout_exercises (workout_id, exercise_id) VALUES (2, 8);
INSERT INTO fitkick_workout_exercises (workout_id, exercise_id) VALUES (2, 9);