INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Back Squat', 'Anaerobic', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Front Squat', 'Anaerobic', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Conventional Deadlift', 'Anaerobic', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Sumo Deadlift', 'Anaerobic', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Barbell Bench Press', 'Anaerobic', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Barbell Overhead Press', 'Anaerobic', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Pull Up', 'Anaerobic', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Push Up', 'Anaerobic', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Run', 'Aerobic', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Swim', 'Aerobic', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Row', 'Aerobic', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Bike', 'Aerobic', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Box Jump', 'Mobility', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Shuttle Sprints', 'Mobility', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Lateral Plyometric Jumps', 'Mobility', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('High Knee Drills', 'Mobility', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Side-to-Side Drills', 'Mobility', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Downward Facing Dog', 'Mobility', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Warrior 1', 'Mobility', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Warrior 2', 'Mobility', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Plank Pose', 'Mobility', '', 1);
INSERT INTO fitkick_exercise (name, exercise_type, notes, owner_id) VALUES ('Cat-Cow Stretch', 'Mobility', '', 1);