# Generated by Django 4.0.3 on 2022-04-15 22:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitkick', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None),
        ),
    ]
