# Generated by Django 4.0.3 on 2022-04-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitkick', '0002_alter_workout_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('Aerobic', 'Aerobic'), ('Anaerobic', 'Anaerobic'), ('Mobility', 'Aobility')], default='', max_length=10),
        ),
    ]
