# Generated by Django 4.0.3 on 2022-04-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitkick', '0003_alter_exerciseinfo_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinfo',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
