# Generated by Django 4.0.3 on 2022-04-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitkick', '0003_alter_exercise_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
    ]
