# Generated by Django 4.0.3 on 2022-04-16 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitkick', '0004_remove_exercise_sets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='owner',
            new_name='workout_owner',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_info_owner',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='notes',
        ),
        migrations.CreateModel(
            name='ExerciseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_infos', to='fitkick.exercise')),
                ('exercise_info_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_infos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
