# Generated by Django 4.0.3 on 2022-05-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitkick', '0004_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
