# Generated by Django 4.0.3 on 2022-04-17 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitkick', '0004_alter_exerciseinfo_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinfo',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_infos', to='fitkick.exercise'),
        ),
    ]
