# Generated by Django 4.0.3 on 2022-04-16 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitkick', '0005_rename_owner_workout_workout_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='exerciseinfo',
            old_name='exercise_info_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='workout_owner',
            new_name='owner',
        ),
    ]
