# Generated by Django 4.0.3 on 2022-05-01 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitkick', '0006_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(default=datetime.date(2022, 5, 1)),
        ),
    ]
