# Generated by Django 4.0.3 on 2022-04-16 05:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitkick', '0006_rename_exercise_owner_exercise_owner_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exerciseinfo',
            unique_together={('owner', 'exercise')},
        ),
    ]
