# Generated by Django 4.0.3 on 2022-05-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitkick', '0007_alter_event_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(),
        ),
    ]
