# Generated by Django 4.0.3 on 2022-04-16 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitkick', '0007_alter_exerciseinfo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinfo',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_info', to='fitkick.exercise'),
        ),
    ]
