# Generated by Django 4.0.3 on 2022-05-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitkick', '0008_alter_event_end_alter_event_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
    ]
